site_name: ClearGauntlets
site_url: https://cleargauntlets.github.io
nav:
  - Home: index.md
  - Parts List: parts_list.md
  - Guides:
    - Power Module: guides/power.md
    - Wiring: guides/wiring.md
  - Projects:
    - Overview: projects/overview.md
    - Main PCB: projects/mainPCB-revB.md
    - Joystick: projects/joystick-PCB.md
  - Blogs:
    - More Accessible Tracker:
      - blogs/mat/mat.md
    - Willard:
      - blogs/willard/2023-02-21.md
  - Photos: photos.md
extra_css:
  - css/extra.css

theme:
  name: materia
