site_name: ClearGauntlets
site_url: https://cleargauntlets.github.io
nav:
  - Home: index.md
  - Docs:
    - Parts List: docs/parts_list.md
    - Mechanical: docs/mechanical.md
    - Electrical: docs/electrical.md
    - Power: docs/power.md
  - Blogs:
    - More Accessible Tracker: blogs/mat/mat.md
    - Willard:
      - blogs/willard/2023-02-21.md
  - Photos: photos.md
extra_css:
  - css/extra.css

theme:
  name: materia
