site_name: ClearGauntlets
site_url: https://cleargauntlets.github.io
nav:
  - Home: index.md
  - Blogs:
    - Willard:
      - blogs/willard/2023-02-21.md
  - Projects:
    - Overview: project/overview.md
    - Main PCB: project/mainPCB-revB.md
    - Joystick: project/joystick-PCB.md
  - Parts List: parts_list.md
  - Photos: photos.md

theme:
  name: materia
